"""criacao inicial

Revision ID: 5636c6c16f82
Revises: 09ec9c8d283b
Create Date: 2026-07-20 08:55:54.436928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5636c6c16f82'
down_revision: Union[str, Sequence[str], None] = '09ec9c8d283b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracoes', sa.Column('start_page_token', sa.String(length=255), nullable=True))
    op.add_column('configuracoes', sa.Column('ultima_sincronizacao', sa.DateTime(), nullable=True))
    op.add_column('configuracoes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('configuracoes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('diretorios', sa.Column('drive_parent_id', sa.String(length=255), nullable=True))
    op.add_column('diretorios', sa.Column('modified_time', sa.DateTime(), nullable=True))
    op.add_column('diretorios', sa.Column('ultima_sincronizacao', sa.DateTime(), nullable=True))
    op.add_column('diretorios', sa.Column('sincronizado', sa.Boolean(), nullable=False))
    op.add_column('diretorios', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('diretorios', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('documentos', sa.Column('sincronizado', sa.Boolean(), nullable=False))
    op.add_column('documentos', sa.Column('drive_parent_id', sa.String(length=255), nullable=True))
    op.add_column('documentos', sa.Column('modified_time', sa.DateTime(), nullable=True))
    op.alter_column('documentos', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documentos', 'diretorio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documentos', 'usuario_upload',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentos', 'usuario_upload',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documentos', 'diretorio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documentos', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('documentos', 'modified_time')
    op.drop_column('documentos', 'drive_parent_id')
    op.drop_column('documentos', 'sincronizado')
    op.alter_column('diretorios', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('diretorios', 'updated_at')
    op.drop_column('diretorios', 'sincronizado')
    op.drop_column('diretorios', 'ultima_sincronizacao')
    op.drop_column('diretorios', 'modified_time')
    op.drop_column('diretorios', 'drive_parent_id')
    op.drop_column('configuracoes', 'updated_at')
    op.drop_column('configuracoes', 'created_at')
    op.drop_column('configuracoes', 'ultima_sincronizacao')
    op.drop_column('configuracoes', 'start_page_token')
    # ### end Alembic commands ###
